import { dirname } from 'path'
import { fileURLToPath } from 'url'
import { FlatCompat } from '@eslint/eslintrc'
import tseslint from 'typescript-eslint'
import nextPlugin from '@next/eslint-plugin-next'
import reactPlugin from 'eslint-plugin-react'
import reactHooksPlugin from 'eslint-plugin-react-hooks'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const compat = new FlatCompat({ baseDirectory: __dirname })

export default tseslint.config(
  // React rules
  {
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    rules: {
      ...reactPlugin.configs.recommended.rules,
      ...reactHooksPlugin.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off', // Not needed in Next.js (auto JSX transform)
    },
    settings: {
      react: { version: 'detect' },
    },
  },

  // Next.js rules — loaded natively to avoid flat config compat warning
  {
    plugins: {
      '@next/next': nextPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },

  // Strict TypeScript rules applied to TS/TSX files only
  {
    files: ['**/*.ts', '**/*.tsx'],
    extends: [
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Explicit return types on exported functions (per code-standards.md)
      '@typescript-eslint/explicit-module-boundary-types': 'error',

      // _ prefix convention for intentionally unused vars
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // No non-null assertions — handle nullability explicitly
      '@typescript-eslint/no-non-null-assertion': 'error',

      // Inline type imports: import { type Foo, bar } from '...'
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
    },
  },

  // Relax rules for shadcn/ui generated components
  {
    files: ['src/components/ui/**/*.tsx'],
    rules: {
      '@typescript-eslint/explicit-module-boundary-types': 'off',
    },
  },

  // Ignore generated and config files from strict TS checking
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      '*.config.mjs',
      '*.config.ts',
      'next-env.d.ts', // auto-generated by Next.js, uses triple-slash refs legitimately
    ],
  },
)
