import { dirname } from 'path'
import { fileURLToPath } from 'url'
import { FlatCompat } from '@eslint/eslintrc'
import tseslint from 'typescript-eslint'
import nextPlugin from '@next/eslint-plugin-next'
import reactPlugin from 'eslint-plugin-react'
import reactHooksPlugin from 'eslint-plugin-react-hooks'
import boundariesPlugin from 'eslint-plugin-boundaries'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const compat = new FlatCompat({ baseDirectory: __dirname })

export default tseslint.config(
  // React rules
  {
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    rules: {
      ...reactPlugin.configs.recommended.rules,
      ...reactHooksPlugin.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off', // Not needed in Next.js (auto JSX transform)
    },
    settings: {
      react: { version: 'detect' },
    },
  },

  // Next.js rules — loaded natively to avoid flat config compat warning
  {
    plugins: {
      '@next/next': nextPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },

  // Strict TypeScript rules applied to TS/TSX files only
  {
    files: ['**/*.ts', '**/*.tsx'],
    extends: [...tseslint.configs.strictTypeChecked, ...tseslint.configs.stylisticTypeChecked],
    languageOptions: {
      parserOptions: {
        project: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Explicit return types on exported functions (per code-standards.md)
      '@typescript-eslint/explicit-module-boundary-types': 'error',

      // _ prefix convention for intentionally unused vars
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // No non-null assertions — handle nullability explicitly
      '@typescript-eslint/no-non-null-assertion': 'error',

      // Inline type imports: import { type Foo, bar } from '...'
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
    },
  },

  // Module boundary enforcement (ADR-009 dependency direction)
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    plugins: {
      boundaries: boundariesPlugin,
    },
    settings: {
      'boundaries/elements': [
        { type: 'shared', pattern: ['src/shared/*'], capture: ['category'] },
        { type: 'auth', pattern: ['src/modules/auth/*'], capture: ['segment'] },
        { type: 'editor', pattern: ['src/modules/editor/*'], capture: ['segment'] },
        { type: 'publishing', pattern: ['src/modules/publishing/*'], capture: ['segment'] },
        { type: 'dashboard', pattern: ['src/modules/dashboard/*'], capture: ['segment'] },
        { type: 'app', pattern: ['src/app/*'], capture: ['segment'] },
        { type: 'ui', pattern: ['src/components/ui/*'], capture: ['segment'] },
      ],
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          rules: [
            // shared → nothing (base layer, no module imports)
            { from: { type: 'shared' }, allow: { to: { type: ['shared', 'ui'] } } },
            // auth → shared only
            { from: { type: 'auth' }, allow: { to: { type: ['shared', 'auth', 'ui'] } } },
            // editor → auth + shared
            {
              from: { type: 'editor' },
              allow: { to: { type: ['shared', 'auth', 'editor', 'ui'] } },
            },
            // publishing → editor + auth + shared
            {
              from: { type: 'publishing' },
              allow: { to: { type: ['shared', 'auth', 'editor', 'publishing', 'ui'] } },
            },
            // dashboard → all modules + shared
            {
              from: { type: 'dashboard' },
              allow: {
                to: { type: ['shared', 'auth', 'editor', 'publishing', 'dashboard', 'ui'] },
              },
            },
            // app routes → everything (thin composition layer)
            {
              from: { type: 'app' },
              allow: {
                to: { type: ['shared', 'auth', 'editor', 'publishing', 'dashboard', 'app', 'ui'] },
              },
            },
          ],
        },
      ],
    },
  },

  // Relax rules for shadcn/ui generated components
  {
    files: ['src/components/ui/**/*.tsx'],
    rules: {
      '@typescript-eslint/explicit-module-boundary-types': 'off',
    },
  },

  // Ignore generated and config files from strict TS checking
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      '*.config.mjs',
      '*.config.ts',
      'next-env.d.ts', // auto-generated by Next.js, uses triple-slash refs legitimately
    ],
  },
)
