import { type BlockTemplate } from './block-template-types'
import { badge, button, container, heading, text } from './block-element-factories'

/** 3-tier elevated pricing cards. */
export const PRICING_TEMPLATE_1: BlockTemplate = {
  variantStyleId: 'pricing-1',
  label: '3 Tier Cards',
  layout: { type: 'grid', columns: 3, gap: 24, align: 'center', verticalAlign: 'top' },
  background: { type: 'color', value: '#f9fafb', valueToken: 'surface' },
  padding: { top: 96, bottom: 96, left: 40, right: 40 },
  createElements: () => [
    // Starter tier
    container(
      0,
      [
        badge(0, 'Starter', {
          fontSize: 12,
          fontWeight: 700,
          color: '#6b7280',
          colorToken: 'text-muted',
          letterSpacing: '0.08em',
        }),
        heading(0, '$9', 2, {
          fontSize: 48,
          fontWeight: 800,
          color: '#111827',
          colorToken: 'text-primary',
          textAlign: 'left',
          lineHeight: 1,
          marginTop: 8,
        }),
        text(0, 'per month', {
          fontSize: 14,
          color: '#9ca3af',
          colorToken: 'text-muted',
          textAlign: 'left',
          marginTop: 2,
        }),
        text(0, '3 landing pages\nBasic analytics\nCommunity support', {
          fontSize: 14,
          color: '#4b5563',
          colorToken: 'text-secondary',
          textAlign: 'left',
          lineHeight: 2,
          marginTop: 16,
        }),
        button(0, 'Get Started', {
          fontSize: 14,
          fontWeight: 600,
          borderRadius: 8,
          padding: { top: 12, bottom: 12, left: 20, right: 20 },
          backgroundColor: '#f3f4f6',
          backgroundColorToken: 'surface',
          color: '#374151',
          colorToken: 'text-secondary',
          marginTop: 8,
        }),
      ],
      {
        backgroundColor: '#ffffff',
        borderRadius: 20,
        boxShadow: '0 4px 24px rgba(0,0,0,0.07)',
        border: '1px solid rgba(0,0,0,0.07)',
        padding: { top: 36, bottom: 36, left: 32, right: 32 },
      },
    ),
    // Pro tier — primary brand color
    container(
      1,
      [
        badge(0, '✦ Most Popular', {
          fontSize: 12,
          fontWeight: 700,
          color: '#2563eb',
          colorToken: 'primary',
          letterSpacing: '0.06em',
        }),
        heading(0, '$29', 2, {
          fontSize: 48,
          fontWeight: 800,
          color: '#2563eb',
          colorToken: 'primary',
          textAlign: 'left',
          lineHeight: 1,
          marginTop: 8,
        }),
        text(0, 'per month', {
          fontSize: 14,
          color: '#9ca3af',
          colorToken: 'text-muted',
          textAlign: 'left',
          marginTop: 2,
        }),
        text(0, 'Unlimited pages\nA/B testing\nCustom domains\nPriority support', {
          fontSize: 14,
          color: '#4b5563',
          colorToken: 'text-secondary',
          textAlign: 'left',
          lineHeight: 2,
          marginTop: 16,
        }),
        button(0, 'Start Pro Trial →', {
          fontSize: 14,
          fontWeight: 700,
          borderRadius: 8,
          padding: { top: 12, bottom: 12, left: 20, right: 20 },
          backgroundGradient: 'linear-gradient(135deg, #2563eb, #4f46e5)',
          gradientToken: 'primary',
          backgroundColor: '#2563eb',
          backgroundColorToken: 'primary',
          color: '#ffffff',
          colorToken: 'primary-foreground',
          boxShadow: '0 4px 16px rgba(37,99,235,0.35)',
          marginTop: 8,
        }),
      ],
      {
        backgroundColor: '#ffffff',
        borderRadius: 20,
        boxShadow: '0 8px 40px rgba(37,99,235,0.15)',
        border: '2px solid #2563eb',
        padding: { top: 36, bottom: 36, left: 32, right: 32 },
      },
    ),
    // Enterprise tier
    container(
      2,
      [
        badge(0, 'Enterprise', {
          fontSize: 12,
          fontWeight: 700,
          color: '#6b7280',
          colorToken: 'text-muted',
          letterSpacing: '0.08em',
        }),
        heading(0, 'Custom', 2, {
          fontSize: 48,
          fontWeight: 800,
          color: '#111827',
          colorToken: 'text-primary',
          textAlign: 'left',
          lineHeight: 1,
          marginTop: 8,
        }),
        text(0, 'pricing', {
          fontSize: 14,
          color: '#9ca3af',
          colorToken: 'text-muted',
          textAlign: 'left',
          marginTop: 2,
        }),
        text(0, 'SSO & audit logs\nSLA guarantee\nDedicated support\nCustom integrations', {
          fontSize: 14,
          color: '#4b5563',
          colorToken: 'text-secondary',
          textAlign: 'left',
          lineHeight: 2,
          marginTop: 16,
        }),
        button(0, 'Contact Sales', {
          fontSize: 14,
          fontWeight: 600,
          borderRadius: 8,
          padding: { top: 12, bottom: 12, left: 20, right: 20 },
          backgroundColor: '#f3f4f6',
          backgroundColorToken: 'surface',
          color: '#374151',
          colorToken: 'text-secondary',
          marginTop: 8,
        }),
      ],
      {
        backgroundColor: '#ffffff',
        borderRadius: 20,
        boxShadow: '0 4px 24px rgba(0,0,0,0.07)',
        border: '1px solid rgba(0,0,0,0.07)',
        padding: { top: 36, bottom: 36, left: 32, right: 32 },
      },
    ),
  ],
}
