import { type BlockTemplate } from './block-template-types'
import { badge, button, container, heading, text } from '@/shared/lib/block-element-factories'

/** Dark glassmorphism pricing cards. */
export const PRICING_TEMPLATE_3: BlockTemplate = {
  variantStyleId: 'pricing-3',
  label: 'Dark Cards',
  layout: { type: 'grid', columns: 3, gap: 20, align: 'center', verticalAlign: 'top' },
  background: {
    type: 'gradient',
    value: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)',
    valueToken: 'dark',
  },
  padding: { top: 96, bottom: 96, left: 40, right: 40 },
  createElements: () => [
    container(
      0,
      [
        badge(0, 'Starter', {
          fontSize: 11,
          color: '#94a3b8',
          colorToken: 'text-muted',
          letterSpacing: '0.1em',
        }),
        heading(0, '$9', 2, {
          fontSize: 44,
          fontWeight: 800,
          color: '#f8fafc',
          colorToken: 'text-on-dark',
          textAlign: 'left',
          lineHeight: 1,
          marginTop: 10,
        }),
        text(0, '/ month · 3 pages', {
          fontSize: 13,
          color: '#64748b',
          colorToken: 'text-muted',
          textAlign: 'left',
          marginTop: 4,
        }),
        button(0, 'Get Starter', {
          fontSize: 14,
          fontWeight: 600,
          borderRadius: 8,
          padding: { top: 11, bottom: 11, left: 20, right: 20 },
          backgroundColor: 'rgba(255,255,255,0.1)',
          backgroundColorToken: 'surface',
          color: '#e2e8f0',
          colorToken: 'text-on-dark',
          border: '1px solid rgba(255,255,255,0.15)',
          marginTop: 20,
        }),
      ],
      {
        backgroundColor: 'rgba(255,255,255,0.06)',
        borderRadius: 20,
        border: '1px solid rgba(255,255,255,0.1)',
        backdropFilter: 'blur(12px)',
        padding: { top: 36, bottom: 36, left: 28, right: 28 },
      },
    ),
    container(
      1,
      [
        badge(0, '✦ Popular', {
          fontSize: 11,
          color: '#818cf8',
          colorToken: 'accent',
          letterSpacing: '0.1em',
        }),
        heading(0, '$29', 2, {
          fontSize: 44,
          fontWeight: 800,
          color: '#818cf8',
          colorToken: 'accent',
          textAlign: 'left',
          lineHeight: 1,
          marginTop: 10,
        }),
        text(0, '/ month · Unlimited', {
          fontSize: 13,
          color: '#64748b',
          colorToken: 'text-muted',
          textAlign: 'left',
          marginTop: 4,
        }),
        button(0, 'Start Pro →', {
          fontSize: 14,
          fontWeight: 700,
          borderRadius: 8,
          padding: { top: 11, bottom: 11, left: 20, right: 20 },
          backgroundGradient: 'linear-gradient(135deg, #6366f1, #a855f7)',
          gradientToken: 'accent',
          backgroundColor: '#6366f1',
          backgroundColorToken: 'primary',
          color: '#ffffff',
          colorToken: 'primary-foreground',
          boxShadow: '0 4px 20px rgba(99,102,241,0.5)',
          marginTop: 20,
        }),
      ],
      {
        backgroundColor: 'rgba(255,255,255,0.09)',
        borderRadius: 20,
        border: '1px solid rgba(129,140,248,0.4)',
        backdropFilter: 'blur(12px)',
        boxShadow: '0 0 40px rgba(99,102,241,0.2)',
        padding: { top: 36, bottom: 36, left: 28, right: 28 },
      },
    ),
    container(
      2,
      [
        badge(0, 'Enterprise', {
          fontSize: 11,
          color: '#94a3b8',
          colorToken: 'text-muted',
          letterSpacing: '0.1em',
        }),
        heading(0, 'Custom', 2, {
          fontSize: 44,
          fontWeight: 800,
          color: '#f8fafc',
          colorToken: 'text-on-dark',
          textAlign: 'left',
          lineHeight: 1,
          marginTop: 10,
        }),
        text(0, 'pricing · Tailored SLA', {
          fontSize: 13,
          color: '#64748b',
          colorToken: 'text-muted',
          textAlign: 'left',
          marginTop: 4,
        }),
        button(0, 'Contact Sales', {
          fontSize: 14,
          fontWeight: 600,
          borderRadius: 8,
          padding: { top: 11, bottom: 11, left: 20, right: 20 },
          backgroundColor: 'rgba(255,255,255,0.1)',
          backgroundColorToken: 'surface',
          color: '#e2e8f0',
          colorToken: 'text-on-dark',
          border: '1px solid rgba(255,255,255,0.15)',
          marginTop: 20,
        }),
      ],
      {
        backgroundColor: 'rgba(255,255,255,0.06)',
        borderRadius: 20,
        border: '1px solid rgba(255,255,255,0.1)',
        backdropFilter: 'blur(12px)',
        padding: { top: 36, bottom: 36, left: 28, right: 28 },
      },
    ),
  ],
}
