import { type BlockTemplate } from './block-template-types'
import { badge, button, heading, image, text } from '@/shared/lib/block-element-factories'

export const HERO_TEMPLATES: BlockTemplate[] = [
  {
    // Centered with subtle gradient + eyebrow badge
    variantStyleId: 'hero-1',
    label: 'Centered Gradient',
    layout: { type: 'stack', gap: 24, align: 'center', verticalAlign: 'center' },
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #ffffff 0%, #eff6ff 60%, #eef2ff 100%)',
      valueToken: 'surface',
    },
    padding: { top: 112, bottom: 112, left: 24, right: 24 },
    createElements: () => [
      badge(0, '✦ Trusted by 10,000 teams worldwide'),
      heading(0, 'Build landing pages that convert', 1, {
        fontSize: 56,
        fontWeight: 800,
        color: '#111827',
        colorToken: 'text-primary',
        lineHeight: 1.1,
        letterSpacing: '-0.02em',
      }),
      text(
        1,
        'A modern drag-and-drop builder that helps you ship faster, run A/B tests, and grow revenue — no code required.',
        { fontSize: 20, lineHeight: 1.7, maxWidth: '600px', color: '#4b5563', colorToken: 'text-secondary' },
      ),
      button(2, 'Get Started Free', {
        fontSize: 16,
        fontWeight: 700,
        borderRadius: 10,
        padding: { top: 14, bottom: 14, left: 36, right: 36 },
        backgroundGradient: 'linear-gradient(135deg, #2563eb, #4f46e5)',
        gradientToken: 'primary',
        backgroundColor: '#2563eb',
        backgroundColorToken: 'primary',
        color: '#ffffff',
        colorToken: 'primary-foreground',
        boxShadow: '0 4px 20px rgba(37, 99, 235, 0.4)',
      }),
      text(3, 'No credit card required · Free 14-day trial', {
        fontSize: 13,
        color: '#9ca3af',
        colorToken: 'text-muted',
      }),
    ],
  },
  {
    // Split layout — text left, image right
    variantStyleId: 'hero-2',
    label: 'Split with Image',
    layout: { type: 'grid', columns: 2, gap: 64, align: 'left', verticalAlign: 'center' },
    background: { type: 'color', value: '#ffffff', valueToken: 'background' },
    padding: { top: 96, bottom: 96, left: 64, right: 64 },
    createElements: () => [
      badge(0, '🚀 New — Version 2.0 is live'),
      heading(0, 'Launch beautiful pages in minutes', 1, {
        fontSize: 48,
        fontWeight: 800,
        color: '#111827',
        colorToken: 'text-primary',
        textAlign: 'left',
        lineHeight: 1.15,
        letterSpacing: '-0.02em',
      }),
      text(
        0,
        'Drag, drop, publish. Every block is pixel-perfect on mobile and desktop. Integrate with your existing tools in one click.',
        { textAlign: 'left', fontSize: 18, lineHeight: 1.7, color: '#4b5563', colorToken: 'text-secondary' },
      ),
      button(0, 'Start Free Trial', {
        fontSize: 15,
        fontWeight: 700,
        borderRadius: 8,
        padding: { top: 14, bottom: 14, left: 32, right: 32 },
        backgroundGradient: 'linear-gradient(135deg, #2563eb, #4f46e5)',
        gradientToken: 'primary',
        backgroundColor: '#2563eb',
        backgroundColorToken: 'primary',
        color: '#ffffff',
        colorToken: 'primary-foreground',
        boxShadow: '0 4px 16px rgba(37, 99, 235, 0.35)',
      }),
      image(1, 'Product dashboard screenshot', { borderRadius: 16, boxShadow: '0 24px 64px rgba(0,0,0,0.15)' }),
    ],
  },
  {
    // Dark glassmorphism — deep gradient bg with glassy card feel
    variantStyleId: 'hero-3',
    label: 'Dark Glassmorphism',
    layout: { type: 'stack', gap: 28, align: 'center', verticalAlign: 'center' },
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f172a 100%)',
      valueToken: 'dark',
    },
    padding: { top: 120, bottom: 120, left: 24, right: 24 },
    createElements: () => [
      badge(0, '✦ AI-powered · No-code · Enterprise ready', {
        color: '#818cf8',
        colorToken: 'accent',
        border: '1px solid rgba(129, 140, 248, 0.3)',
        borderRadius: 999,
        padding: { top: 6, bottom: 6, left: 16, right: 16 },
        backgroundColor: 'rgba(129, 140, 248, 0.1)',
      }),
      heading(0, 'The future of landing pages is here', 1, {
        fontSize: 60,
        fontWeight: 800,
        color: '#f8fafc',
        colorToken: 'text-on-dark',
        lineHeight: 1.1,
        letterSpacing: '-0.02em',
        maxWidth: '760px',
      }),
      text(
        1,
        'Build, test, and publish in minutes. Backed by real analytics and AI-assisted copy generation.',
        {
          fontSize: 20,
          lineHeight: 1.7,
          maxWidth: '560px',
          color: '#94a3b8',
          colorToken: 'text-muted',
        },
      ),
      button(2, 'Get Early Access', {
        fontSize: 16,
        fontWeight: 700,
        borderRadius: 10,
        padding: { top: 14, bottom: 14, left: 36, right: 36 },
        backgroundGradient: 'linear-gradient(135deg, #6366f1, #a855f7)',
        gradientToken: 'accent',
        backgroundColor: '#6366f1',
        backgroundColorToken: 'accent',
        color: '#ffffff',
        colorToken: 'accent-foreground',
        boxShadow: '0 4px 24px rgba(99, 102, 241, 0.5)',
      }),
    ],
  },
  {
    // Minimal — oversized typography, no background fill, editorial feel
    variantStyleId: 'hero-4',
    label: 'Minimal Editorial',
    layout: { type: 'stack', gap: 20, align: 'center', verticalAlign: 'center' },
    background: { type: 'color', value: '#ffffff', valueToken: 'background' },
    padding: { top: 128, bottom: 128, left: 24, right: 24 },
    createElements: () => [
      heading(0, 'Pages that\nconvert.', 1, {
        fontSize: 72,
        fontWeight: 900,
        color: '#111827',
        colorToken: 'text-primary',
        lineHeight: 1.0,
        letterSpacing: '-0.04em',
      }),
      text(
        1,
        'Ship landing pages fast. A/B test everything. Grow with confidence.',
        { fontSize: 20, maxWidth: '480px', color: '#6b7280', colorToken: 'text-muted', lineHeight: 1.6 },
      ),
      button(2, 'Start building →', {
        fontSize: 16,
        fontWeight: 600,
        borderRadius: 0,
        padding: { top: 14, bottom: 14, left: 0, right: 0 },
        backgroundColor: 'transparent',
        color: '#111827',
        colorToken: 'text-primary',
        border: '0 0 2px 0',
        letterSpacing: '0.02em',
      }),
    ],
  },
]
