import { type BlockTemplate } from './block-template-types'
import { badge, button, container, heading, text } from './block-element-factories'

export const PRICING_TEMPLATES: BlockTemplate[] = [
  {
    // Elevated cards — 3 tiers, each tier is a container
    variantStyleId: 'pricing-1',
    label: '3 Tier Cards',
    layout: { type: 'grid', columns: 3, gap: 24, align: 'center', verticalAlign: 'top' },
    background: { type: 'color', value: '#f9fafb', valueToken: 'surface' },
    padding: { top: 96, bottom: 96, left: 40, right: 40 },
    createElements: () => [
      // Starter tier
      container(
        0,
        [
          badge(0, 'Starter', {
            fontSize: 12,
            fontWeight: 700,
            color: '#6b7280',
            colorToken: 'text-muted',
            letterSpacing: '0.08em',
          }),
          heading(0, '$9', 2, {
            fontSize: 48,
            fontWeight: 800,
            color: '#111827',
            colorToken: 'text-primary',
            textAlign: 'left',
            lineHeight: 1,
            marginTop: 8,
          }),
          text(0, 'per month', {
            fontSize: 14,
            color: '#9ca3af',
            colorToken: 'text-muted',
            textAlign: 'left',
            marginTop: 2,
          }),
          text(0, '3 landing pages\nBasic analytics\nCommunity support', {
            fontSize: 14,
            color: '#4b5563',
            colorToken: 'text-secondary',
            textAlign: 'left',
            lineHeight: 2,
            marginTop: 16,
          }),
          button(0, 'Get Started', {
            fontSize: 14,
            fontWeight: 600,
            borderRadius: 8,
            padding: { top: 12, bottom: 12, left: 20, right: 20 },
            backgroundColor: '#f3f4f6',
            backgroundColorToken: 'surface',
            color: '#374151',
            colorToken: 'text-secondary',
            marginTop: 8,
          }),
        ],
        {
          backgroundColor: '#ffffff',
          borderRadius: 20,
          boxShadow: '0 4px 24px rgba(0,0,0,0.07)',
          border: '1px solid rgba(0,0,0,0.07)',
          padding: { top: 36, bottom: 36, left: 32, right: 32 },
        },
      ),
      // Pro tier — primary brand color
      container(
        1,
        [
          badge(0, '✦ Most Popular', {
            fontSize: 12,
            fontWeight: 700,
            color: '#2563eb',
            colorToken: 'primary',
            letterSpacing: '0.06em',
          }),
          heading(0, '$29', 2, {
            fontSize: 48,
            fontWeight: 800,
            color: '#2563eb',
            colorToken: 'primary',
            textAlign: 'left',
            lineHeight: 1,
            marginTop: 8,
          }),
          text(0, 'per month', {
            fontSize: 14,
            color: '#9ca3af',
            colorToken: 'text-muted',
            textAlign: 'left',
            marginTop: 2,
          }),
          text(0, 'Unlimited pages\nA/B testing\nCustom domains\nPriority support', {
            fontSize: 14,
            color: '#4b5563',
            colorToken: 'text-secondary',
            textAlign: 'left',
            lineHeight: 2,
            marginTop: 16,
          }),
          button(0, 'Start Pro Trial →', {
            fontSize: 14,
            fontWeight: 700,
            borderRadius: 8,
            padding: { top: 12, bottom: 12, left: 20, right: 20 },
            backgroundGradient: 'linear-gradient(135deg, #2563eb, #4f46e5)',
            gradientToken: 'primary',
            backgroundColor: '#2563eb',
            backgroundColorToken: 'primary',
            color: '#ffffff',
            colorToken: 'primary-foreground',
            boxShadow: '0 4px 16px rgba(37,99,235,0.35)',
            marginTop: 8,
          }),
        ],
        {
          backgroundColor: '#ffffff',
          borderRadius: 20,
          boxShadow: '0 8px 40px rgba(37,99,235,0.15)',
          border: '2px solid #2563eb',
          padding: { top: 36, bottom: 36, left: 32, right: 32 },
        },
      ),
      // Enterprise tier
      container(
        2,
        [
          badge(0, 'Enterprise', {
            fontSize: 12,
            fontWeight: 700,
            color: '#6b7280',
            colorToken: 'text-muted',
            letterSpacing: '0.08em',
          }),
          heading(0, 'Custom', 2, {
            fontSize: 48,
            fontWeight: 800,
            color: '#111827',
            colorToken: 'text-primary',
            textAlign: 'left',
            lineHeight: 1,
            marginTop: 8,
          }),
          text(0, 'pricing', {
            fontSize: 14,
            color: '#9ca3af',
            colorToken: 'text-muted',
            textAlign: 'left',
            marginTop: 2,
          }),
          text(0, 'SSO & audit logs\nSLA guarantee\nDedicated support\nCustom integrations', {
            fontSize: 14,
            color: '#4b5563',
            colorToken: 'text-secondary',
            textAlign: 'left',
            lineHeight: 2,
            marginTop: 16,
          }),
          button(0, 'Contact Sales', {
            fontSize: 14,
            fontWeight: 600,
            borderRadius: 8,
            padding: { top: 12, bottom: 12, left: 20, right: 20 },
            backgroundColor: '#f3f4f6',
            backgroundColorToken: 'surface',
            color: '#374151',
            colorToken: 'text-secondary',
            marginTop: 8,
          }),
        ],
        {
          backgroundColor: '#ffffff',
          borderRadius: 20,
          boxShadow: '0 4px 24px rgba(0,0,0,0.07)',
          border: '1px solid rgba(0,0,0,0.07)',
          padding: { top: 36, bottom: 36, left: 32, right: 32 },
        },
      ),
    ],
  },
  {
    // Minimal 2-tier cards
    variantStyleId: 'pricing-2',
    label: '2 Tier Minimal',
    layout: { type: 'grid', columns: 2, gap: 40, align: 'center', verticalAlign: 'top' },
    background: { type: 'color', value: '#ffffff', valueToken: 'background' },
    padding: { top: 96, bottom: 96, left: 64, right: 64 },
    createElements: () => [
      container(
        0,
        [
          heading(0, 'Free', 3, {
            fontSize: 20,
            fontWeight: 700,
            color: '#111827',
            colorToken: 'text-primary',
            textAlign: 'left',
          }),
          heading(0, '$0 / month', 2, {
            fontSize: 36,
            fontWeight: 800,
            color: '#111827',
            colorToken: 'text-primary',
            textAlign: 'left',
            letterSpacing: '-0.02em',
            marginTop: 8,
          }),
          text(0, 'Perfect for personal projects and experimentation.', {
            fontSize: 15,
            textAlign: 'left',
            lineHeight: 1.6,
            marginTop: 8,
          }),
          button(0, 'Get Started Free', {
            fontSize: 14,
            fontWeight: 600,
            borderRadius: 8,
            padding: { top: 12, bottom: 12, left: 24, right: 24 },
            backgroundColor: '#f3f4f6',
            backgroundColorToken: 'surface',
            color: '#111827',
            colorToken: 'text-primary',
            marginTop: 8,
          }),
        ],
        {
          borderRadius: 16,
          border: '1px solid #e5e7eb',
          padding: { top: 40, bottom: 40, left: 36, right: 36 },
        },
      ),
      container(
        1,
        [
          heading(0, 'Pro', 3, {
            fontSize: 20,
            fontWeight: 700,
            color: '#2563eb',
            colorToken: 'primary',
            textAlign: 'left',
          }),
          heading(0, '$19 / month', 2, {
            fontSize: 36,
            fontWeight: 800,
            color: '#2563eb',
            colorToken: 'primary',
            textAlign: 'left',
            letterSpacing: '-0.02em',
            marginTop: 8,
          }),
          text(0, 'Unlimited pages, A/B testing, custom domains, and priority support.', {
            fontSize: 15,
            textAlign: 'left',
            lineHeight: 1.6,
            marginTop: 8,
          }),
          button(0, 'Upgrade to Pro', {
            fontSize: 14,
            fontWeight: 700,
            borderRadius: 8,
            padding: { top: 12, bottom: 12, left: 24, right: 24 },
            backgroundGradient: 'linear-gradient(135deg, #2563eb, #4f46e5)',
            gradientToken: 'primary',
            backgroundColor: '#2563eb',
            backgroundColorToken: 'primary',
            color: '#ffffff',
            colorToken: 'primary-foreground',
            marginTop: 8,
          }),
        ],
        {
          borderRadius: 16,
          border: '1px solid #e5e7eb',
          padding: { top: 40, bottom: 40, left: 36, right: 36 },
        },
      ),
    ],
  },
  {
    // Dark glassmorphism pricing cards
    variantStyleId: 'pricing-3',
    label: 'Dark Cards',
    layout: { type: 'grid', columns: 3, gap: 20, align: 'center', verticalAlign: 'top' },
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)',
      valueToken: 'dark',
    },
    padding: { top: 96, bottom: 96, left: 40, right: 40 },
    createElements: () => [
      container(
        0,
        [
          badge(0, 'Starter', {
            fontSize: 11,
            color: '#94a3b8',
            colorToken: 'text-muted',
            letterSpacing: '0.1em',
          }),
          heading(0, '$9', 2, {
            fontSize: 44,
            fontWeight: 800,
            color: '#f8fafc',
            colorToken: 'text-on-dark',
            textAlign: 'left',
            lineHeight: 1,
            marginTop: 10,
          }),
          text(0, '/ month · 3 pages', {
            fontSize: 13,
            color: '#64748b',
            colorToken: 'text-muted',
            textAlign: 'left',
            marginTop: 4,
          }),
          button(0, 'Get Starter', {
            fontSize: 14,
            fontWeight: 600,
            borderRadius: 8,
            padding: { top: 11, bottom: 11, left: 20, right: 20 },
            backgroundColor: 'rgba(255,255,255,0.1)',
            backgroundColorToken: 'surface',
            color: '#e2e8f0',
            colorToken: 'text-on-dark',
            border: '1px solid rgba(255,255,255,0.15)',
            marginTop: 20,
          }),
        ],
        {
          backgroundColor: 'rgba(255,255,255,0.06)',
          borderRadius: 20,
          border: '1px solid rgba(255,255,255,0.1)',
          backdropFilter: 'blur(12px)',
          padding: { top: 36, bottom: 36, left: 28, right: 28 },
        },
      ),
      container(
        1,
        [
          badge(0, '✦ Popular', {
            fontSize: 11,
            color: '#818cf8',
            colorToken: 'accent',
            letterSpacing: '0.1em',
          }),
          heading(0, '$29', 2, {
            fontSize: 44,
            fontWeight: 800,
            color: '#818cf8',
            colorToken: 'accent',
            textAlign: 'left',
            lineHeight: 1,
            marginTop: 10,
          }),
          text(0, '/ month · Unlimited', {
            fontSize: 13,
            color: '#64748b',
            colorToken: 'text-muted',
            textAlign: 'left',
            marginTop: 4,
          }),
          button(0, 'Start Pro →', {
            fontSize: 14,
            fontWeight: 700,
            borderRadius: 8,
            padding: { top: 11, bottom: 11, left: 20, right: 20 },
            backgroundGradient: 'linear-gradient(135deg, #6366f1, #a855f7)',
            gradientToken: 'accent',
            backgroundColor: '#6366f1',
            backgroundColorToken: 'primary',
            color: '#ffffff',
            colorToken: 'primary-foreground',
            boxShadow: '0 4px 20px rgba(99,102,241,0.5)',
            marginTop: 20,
          }),
        ],
        {
          backgroundColor: 'rgba(255,255,255,0.09)',
          borderRadius: 20,
          border: '1px solid rgba(129,140,248,0.4)',
          backdropFilter: 'blur(12px)',
          boxShadow: '0 0 40px rgba(99,102,241,0.2)',
          padding: { top: 36, bottom: 36, left: 28, right: 28 },
        },
      ),
      container(
        2,
        [
          badge(0, 'Enterprise', {
            fontSize: 11,
            color: '#94a3b8',
            colorToken: 'text-muted',
            letterSpacing: '0.1em',
          }),
          heading(0, 'Custom', 2, {
            fontSize: 44,
            fontWeight: 800,
            color: '#f8fafc',
            colorToken: 'text-on-dark',
            textAlign: 'left',
            lineHeight: 1,
            marginTop: 10,
          }),
          text(0, 'pricing · Tailored SLA', {
            fontSize: 13,
            color: '#64748b',
            colorToken: 'text-muted',
            textAlign: 'left',
            marginTop: 4,
          }),
          button(0, 'Contact Sales', {
            fontSize: 14,
            fontWeight: 600,
            borderRadius: 8,
            padding: { top: 11, bottom: 11, left: 20, right: 20 },
            backgroundColor: 'rgba(255,255,255,0.1)',
            backgroundColorToken: 'surface',
            color: '#e2e8f0',
            colorToken: 'text-on-dark',
            border: '1px solid rgba(255,255,255,0.15)',
            marginTop: 20,
          }),
        ],
        {
          backgroundColor: 'rgba(255,255,255,0.06)',
          borderRadius: 20,
          border: '1px solid rgba(255,255,255,0.1)',
          backdropFilter: 'blur(12px)',
          padding: { top: 36, bottom: 36, left: 28, right: 28 },
        },
      ),
    ],
  },
]
