import { type BlockTemplate } from './block-template-types'
import { badge, button, heading, text } from './block-element-factories'

export const PRICING_TEMPLATES: BlockTemplate[] = [
  {
    // Elevated cards — 3 tiers, Pro tier visually distinguished via element colors
    variantStyleId: 'pricing-1',
    label: '3 Tier Cards',
    layout: { type: 'grid', columns: 3, gap: 24, align: 'center', verticalAlign: 'top' },
    background: { type: 'color', value: '#f9fafb', valueToken: 'surface' },
    padding: { top: 96, bottom: 96, left: 40, right: 40 },
    slotStyle: {
      backgroundColor: '#ffffff',
      borderRadius: 20,
      boxShadow: '0 4px 24px rgba(0,0,0,0.07)',
      border: '1px solid rgba(0,0,0,0.07)',
      padding: { top: 36, bottom: 36, left: 32, right: 32 },
    },
    createElements: () => [
      // Starter tier
      badge(0, 'Starter', {
        fontSize: 12,
        fontWeight: 700,
        color: '#6b7280',
        colorToken: 'text-muted',
        letterSpacing: '0.08em',
      }),
      heading(0, '$9', 2, {
        fontSize: 48,
        fontWeight: 800,
        color: '#111827',
        colorToken: 'text-primary',
        textAlign: 'left',
        lineHeight: 1,
        marginTop: 8,
      }),
      text(0, 'per month', {
        fontSize: 14,
        color: '#9ca3af',
        colorToken: 'text-muted',
        textAlign: 'left',
        marginTop: 2,
      }),
      text(0, '3 landing pages\nBasic analytics\nCommunity support', {
        fontSize: 14,
        color: '#4b5563',
        colorToken: 'text-secondary',
        textAlign: 'left',
        lineHeight: 2,
        marginTop: 16,
      }),
      button(0, 'Get Started', {
        fontSize: 14,
        fontWeight: 600,
        borderRadius: 8,
        padding: { top: 12, bottom: 12, left: 20, right: 20 },
        backgroundColor: '#f3f4f6',
        backgroundColorToken: 'surface',
        color: '#374151',
        colorToken: 'text-secondary',
        marginTop: 8,
      }),

      // Pro tier — primary brand color to signal value
      badge(1, '✦ Most Popular', {
        fontSize: 12,
        fontWeight: 700,
        color: '#2563eb',
        colorToken: 'primary',
        letterSpacing: '0.06em',
      }),
      heading(1, '$29', 2, {
        fontSize: 48,
        fontWeight: 800,
        color: '#2563eb',
        colorToken: 'primary',
        textAlign: 'left',
        lineHeight: 1,
        marginTop: 8,
      }),
      text(1, 'per month', {
        fontSize: 14,
        color: '#9ca3af',
        colorToken: 'text-muted',
        textAlign: 'left',
        marginTop: 2,
      }),
      text(1, 'Unlimited pages\nA/B testing\nCustom domains\nPriority support', {
        fontSize: 14,
        color: '#4b5563',
        colorToken: 'text-secondary',
        textAlign: 'left',
        lineHeight: 2,
        marginTop: 16,
      }),
      button(1, 'Start Pro Trial →', {
        fontSize: 14,
        fontWeight: 700,
        borderRadius: 8,
        padding: { top: 12, bottom: 12, left: 20, right: 20 },
        backgroundGradient: 'linear-gradient(135deg, #2563eb, #4f46e5)',
        gradientToken: 'primary',
        backgroundColor: '#2563eb',
        backgroundColorToken: 'primary',
        color: '#ffffff',
        colorToken: 'primary-foreground',
        boxShadow: '0 4px 16px rgba(37,99,235,0.35)',
        marginTop: 8,
      }),

      // Enterprise tier
      badge(2, 'Enterprise', {
        fontSize: 12,
        fontWeight: 700,
        color: '#6b7280',
        colorToken: 'text-muted',
        letterSpacing: '0.08em',
      }),
      heading(2, 'Custom', 2, {
        fontSize: 48,
        fontWeight: 800,
        color: '#111827',
        colorToken: 'text-primary',
        textAlign: 'left',
        lineHeight: 1,
        marginTop: 8,
      }),
      text(2, 'pricing', {
        fontSize: 14,
        color: '#9ca3af',
        colorToken: 'text-muted',
        textAlign: 'left',
        marginTop: 2,
      }),
      text(2, 'SSO & audit logs\nSLA guarantee\nDedicated support\nCustom integrations', {
        fontSize: 14,
        color: '#4b5563',
        colorToken: 'text-secondary',
        textAlign: 'left',
        lineHeight: 2,
        marginTop: 16,
      }),
      button(2, 'Contact Sales', {
        fontSize: 14,
        fontWeight: 600,
        borderRadius: 8,
        padding: { top: 12, bottom: 12, left: 20, right: 20 },
        backgroundColor: '#f3f4f6',
        backgroundColorToken: 'surface',
        color: '#374151',
        colorToken: 'text-secondary',
        marginTop: 8,
      }),
    ],
  },
  {
    // Minimal 2-tier — clean, no card chrome
    variantStyleId: 'pricing-2',
    label: '2 Tier Minimal',
    layout: { type: 'grid', columns: 2, gap: 40, align: 'center', verticalAlign: 'top' },
    background: { type: 'color', value: '#ffffff', valueToken: 'background' },
    padding: { top: 96, bottom: 96, left: 64, right: 64 },
    slotStyle: {
      borderRadius: 16,
      border: '1px solid #e5e7eb',
      padding: { top: 40, bottom: 40, left: 36, right: 36 },
    },
    createElements: () => [
      heading(0, 'Free', 3, {
        fontSize: 20,
        fontWeight: 700,
        color: '#111827',
        colorToken: 'text-primary',
        textAlign: 'left',
      }),
      heading(0, '$0 / month', 2, {
        fontSize: 36,
        fontWeight: 800,
        color: '#111827',
        colorToken: 'text-primary',
        textAlign: 'left',
        letterSpacing: '-0.02em',
        marginTop: 8,
      }),
      text(0, 'Perfect for personal projects and experimentation.', {
        fontSize: 15,
        textAlign: 'left',
        lineHeight: 1.6,
        marginTop: 8,
      }),
      button(0, 'Get Started Free', {
        fontSize: 14,
        fontWeight: 600,
        borderRadius: 8,
        padding: { top: 12, bottom: 12, left: 24, right: 24 },
        backgroundColor: '#f3f4f6',
        backgroundColorToken: 'surface',
        color: '#111827',
        colorToken: 'text-primary',
        marginTop: 8,
      }),

      heading(1, 'Pro', 3, {
        fontSize: 20,
        fontWeight: 700,
        color: '#2563eb',
        colorToken: 'primary',
        textAlign: 'left',
      }),
      heading(1, '$19 / month', 2, {
        fontSize: 36,
        fontWeight: 800,
        color: '#2563eb',
        colorToken: 'primary',
        textAlign: 'left',
        letterSpacing: '-0.02em',
        marginTop: 8,
      }),
      text(1, 'Unlimited pages, A/B testing, custom domains, and priority support.', {
        fontSize: 15,
        textAlign: 'left',
        lineHeight: 1.6,
        marginTop: 8,
      }),
      button(1, 'Upgrade to Pro', {
        fontSize: 14,
        fontWeight: 700,
        borderRadius: 8,
        padding: { top: 12, bottom: 12, left: 24, right: 24 },
        backgroundGradient: 'linear-gradient(135deg, #2563eb, #4f46e5)',
        gradientToken: 'primary',
        backgroundColor: '#2563eb',
        backgroundColorToken: 'primary',
        color: '#ffffff',
        colorToken: 'primary-foreground',
        marginTop: 8,
      }),
    ],
  },
  {
    // Dark glassmorphism pricing
    variantStyleId: 'pricing-3',
    label: 'Dark Cards',
    layout: { type: 'grid', columns: 3, gap: 20, align: 'center', verticalAlign: 'top' },
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)',
      valueToken: 'dark',
    },
    padding: { top: 96, bottom: 96, left: 40, right: 40 },
    slotStyle: {
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderRadius: 20,
      border: '1px solid rgba(255,255,255,0.1)',
      backdropFilter: 'blur(12px)',
      padding: { top: 36, bottom: 36, left: 28, right: 28 },
    },
    createElements: () => [
      badge(0, 'Starter', {
        fontSize: 11,
        color: '#94a3b8',
        colorToken: 'text-muted',
        letterSpacing: '0.1em',
      }),
      heading(0, '$9', 2, {
        fontSize: 44,
        fontWeight: 800,
        color: '#f8fafc',
        colorToken: 'text-on-dark',
        textAlign: 'left',
        lineHeight: 1,
        marginTop: 10,
      }),
      text(0, '/ month · 3 pages', {
        fontSize: 13,
        color: '#64748b',
        colorToken: 'text-muted',
        textAlign: 'left',
        marginTop: 4,
      }),
      button(0, 'Get Starter', {
        fontSize: 14,
        fontWeight: 600,
        borderRadius: 8,
        padding: { top: 11, bottom: 11, left: 20, right: 20 },
        backgroundColor: 'rgba(255,255,255,0.1)',
        backgroundColorToken: 'surface',
        color: '#e2e8f0',
        colorToken: 'text-on-dark',
        border: '1px solid rgba(255,255,255,0.15)',
        marginTop: 20,
      }),

      badge(1, '✦ Popular', {
        fontSize: 11,
        color: '#818cf8',
        colorToken: 'accent',
        letterSpacing: '0.1em',
      }),
      heading(1, '$29', 2, {
        fontSize: 44,
        fontWeight: 800,
        color: '#818cf8',
        colorToken: 'accent',
        textAlign: 'left',
        lineHeight: 1,
        marginTop: 10,
      }),
      text(1, '/ month · Unlimited', {
        fontSize: 13,
        color: '#64748b',
        colorToken: 'text-muted',
        textAlign: 'left',
        marginTop: 4,
      }),
      button(1, 'Start Pro →', {
        fontSize: 14,
        fontWeight: 700,
        borderRadius: 8,
        padding: { top: 11, bottom: 11, left: 20, right: 20 },
        backgroundGradient: 'linear-gradient(135deg, #6366f1, #a855f7)',
        gradientToken: 'accent',
        backgroundColor: '#6366f1',
        backgroundColorToken: 'primary',
        color: '#ffffff',
        colorToken: 'primary-foreground',
        boxShadow: '0 4px 20px rgba(99,102,241,0.5)',
        marginTop: 20,
      }),

      badge(2, 'Enterprise', {
        fontSize: 11,
        color: '#94a3b8',
        colorToken: 'text-muted',
        letterSpacing: '0.1em',
      }),
      heading(2, 'Custom', 2, {
        fontSize: 44,
        fontWeight: 800,
        color: '#f8fafc',
        colorToken: 'text-on-dark',
        textAlign: 'left',
        lineHeight: 1,
        marginTop: 10,
      }),
      text(2, 'pricing · Tailored SLA', {
        fontSize: 13,
        color: '#64748b',
        colorToken: 'text-muted',
        textAlign: 'left',
        marginTop: 4,
      }),
      button(2, 'Contact Sales', {
        fontSize: 14,
        fontWeight: 600,
        borderRadius: 8,
        padding: { top: 11, bottom: 11, left: 20, right: 20 },
        backgroundColor: 'rgba(255,255,255,0.1)',
        backgroundColorToken: 'surface',
        color: '#e2e8f0',
        colorToken: 'text-on-dark',
        border: '1px solid rgba(255,255,255,0.15)',
        marginTop: 20,
      }),
    ],
  },
]
